services:
  # 1. Pubky.app Social UI
  # client:
  #   container_name: client
  #   build:
  #     context: ./pubky-app
  #     args:
  #       - NPM_TOKEN: ${NPM_TOKEN}
  #   volumes: 
  #     - ./pubky-app:/usr/src/app
  #   environment:
  #     - NEXT_PUBLIC_HOMESERVER=${NEXT_PUBLIC_HOMESERVER}
  #     - NEXT_PUBLIC_PKARR_RELAY=http://localhost:7258
  #   command: [ "npm", "run", "start:prod" ]
  #   networks:
  #     - default
  #   ports:
  #     - 4200:4200

  # 2. Pubky Homeserver
  homeserver:
    container_name: homeserver
    build:
      context: ./pubky-homeserver
    volumes: 
      - ./homeserver.config.toml:/usr/src/app/config.toml
      - .database/homeserver:/usr/src/app/.database/homeserver
    command: homeserver
    networks:
      - default
    ports:
      - 6287:6287

  # 3 Nexus
  # 3.1 Pubky Nexus Service
  nexus-service:
    container_name: nexus-service
    build:
      context: ./pubky-nexus
    command: service
    env_file:
      - ./nexus.env
    ports:
      - 8080:8080
    networks:
      - default
    depends_on:
      - nexus-neo4j
      - nexus-redis

  # 3.2 Pubky Nexus Watcher
  nexus-watcher:
    container_name: nexus-watcher
    build:
      context: ./pubky-nexus
    env_file:
      - ./nexus.env
    command: watcher
    networks:
      - default
    depends_on:
      - nexus-neo4j
      - nexus-redis

  # 3.3 Pubky Nexus Graph
  nexus-neo4j:
    image: neo4j:5.21.2-community
    container_name: nexus-neo4j
    restart: unless-stopped
    ports: 
      - 7474:7474
      - 7687:7687
    networks:
      - default
    volumes:
      # Mount the neo4j configuration file to container    
      - .database/neo4j/conf:/conf
      # Mount the data to container
      - .database/neo4j/data:/data
      - .database/neo4j/logs:/logs
      - ./pubky-nexus/docker/db-graph:/db-graph
    env_file:
      - ./neo4j.env


  # 3.4 Pubky Nexus Index
  nexus-redis:
    image: redis/redis-stack:7.2.0-v11
    container_name: nexus-redis
    ports:
      - 6379:6379
      - 8001:8001 # Redis Insight http://localhost:8001/
    networks:
      - default
    volumes:
      - .database/redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    sysctls:
      - net.core.somaxconn=65535

networks:
  default:
    driver: bridge

volumes:
 backend_storage:
