services:
  # 1. Pubky.app Social UI
  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./Dockerfile.web
    volumes: 
      - ./pubky-app:/usr/src/app
      - ./skunk-works:/skunk-works
    environment:
      - NEXT_PUBLIC_HOMESERVER=${NEXT_PUBLIC_HOMESERVER}
      - NEXT_PUBLIC_PKARR_RELAY=http://localhost:7258
    command: [npx, nx, serve, web]
    networks:
      - default
    ports:
      - 4200:4200

  # 2. Pubky Homeserver
  homeserver:
    container_name: homeserver
    build:
      context: ./pubky-homeserver
    volumes: 
      - ./homeserver.config.toml:/usr/src/app/config.toml
      - .database/homeserver:/usr/src/app/.database/homeserver
    command: homeserver
    networks:
      - default
    ports:
      - 6287:6287

  # 3 Nexus
  # 3.1 Pubky Nexus Service
  nexus-service:
    container_name: nexus-service
    build:
      context: ./pubky-nexus
    command: service
    volumes:
      - ./nexus.env:/usr/src/app/.env
    ports:
      - 8080:8080
    networks:
      - default

  # 3.2 Pubky Nexus Watcher
  nexus-watcher:
    container_name: nexus-watcher
    build:
      context: ./pubky-nexus
    image: nexus-service
    volumes:
      - ./nexus.env:/usr/src/app/.env
    command: watcher
    networks:
      - default

  # 3.3 Pubky Nexus Graph
  nexus-neo4j:
    image: neo4j:5.21.2-community
    container_name: nexus-neo4j
    restart: unless-stopped
    ports: 
      - 7474:7474
      - 7687:7687
    networks:
      - default
    volumes:
      # Mount the neo4j configuration file to container    
      - .database/neo4j/conf:/conf
      # Mount the data to container
      - .database/neo4j/data:/data
      - .database/neo4j/logs:/logs
      - ./pubky-nexus/docker/db-graph:/db-graph
    environment:
      NEO4J_initial_dbms_default__database: ${NEO4J_DB_NAME}
      # IMPORTANT: If you change the auth params and you have already created the config files, will not take effect
      # To restart: docker compose down -v
      NEO4J_AUTH: ${NEO4J_DB_USERNAME}/${NEO4J_PASSWORD}
      # https://neo4j.com/docs/operations-manual/current/docker/configuration/
      # Modify the default configuration
      # Raise memory limits
      NEO4J_server_memory_pagecache_size: 1G
      NEO4J_server_memory_heap_initial__size: 2G
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_apoc_uuid_enabled: false

  # 3.4 Pubky Nexus Index
  nexus-redis:
    image: redis/redis-stack:7.2.0-v11
    container_name: nexus-redis
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - default
    volumes:
      - .database/redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    sysctls:
      - net.core.somaxconn=65535

networks:
  default:
    driver: bridge
