services:
  # 1. Pkarr server
  pkarr:
    container_name: pkarr
    build:
      context: ./pkarr
    volumes: 
      - ./pkarr.config.toml:/config.toml
      - .storage/pkarr:/cache
    command: pkarr-server --config=/config.toml
    # networks:
    #   - default
    # ports:
    #   - 6882:6882
    network_mode: host

  # 2. Pubky Homeserver
  homeserver:
    container_name: homeserver
    restart: always
    build:
      context: ./pubky-core
    volumes: 
      - ./homeserver.config.toml:/config.toml
      - .storage/homeserver:/homeserver
    command: homeserver --config=/config.toml -t pubky_homeserver=info,tower_http=info
    # networks:
    #   - default
    # ports:
    #   - 6287:6287
    depends_on:
      - pkarr
    network_mode: host

  # 3 Nexus
  # 3.1 Pubky Nexus Service
  nexus-service:
    container_name: nexus-service
    build:
      context: ./pubky-nexus
    command: service
    volumes:
      # Mount static files path
      - .storage/static:/static
    env_file:
      - ./nexus.env
    # ports:
    #   - 8080:8080
    # networks:
    #   - default
    network_mode: host
    depends_on:
      - nexus-neo4j
      - nexus-redis

  # 3.2 Pubky Nexus Watcher
  nexus-watcher:
    container_name: nexus-watcher
    build:
      context: ./pubky-nexus
    volumes:
      # Mount static files path
      - .storage/static:/static
    env_file:
      - ./nexus.env
    command: watcher
    # networks:
    #   - default
    # depends_on:
    #   - nexus-neo4j
    #   - nexus-redis
    network_mode: host

  # 3.3 Pubky Nexus Graph
  nexus-neo4j:
    image: neo4j:5.24.2-community
    container_name: nexus-neo4j
    restart: unless-stopped
    # ports: 
    #   - 7474:7474
    #   - 7687:7687
    # networks:
    #   - default
    network_mode: host
    volumes:
      # Mount the neo4j configuration file to container    
      - .storage/neo4j/conf:/conf
      # Mount the data to container
      - .storage/neo4j/data:/data
      - .storage/neo4j/logs:/logs
      - ./pubky-nexus/docker/db-graph:/db-graph
    env_file:
      - ./neo4j.env

  # 3.4 Pubky Nexus Index
  nexus-redis:
    image: redis/redis-stack:7.2.0-v11
    container_name: nexus-redis
    # ports:
    #   - 6379:6379
    #   - 8001:8001 # Redis Insight http://localhost:8001/
    # networks:
    #   - default
    network_mode: host
    volumes:
      - .storage/redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always

  # 4. Pubky.app Social UI
  client:
    container_name: client
    build:
      context: ./pubky-app
    env_file:
      - ./client.env
    command: ["npm", "run", "serve:prod"]
    # networks:
    #   - default
    # ports:
    #   - 4200:4200
    network_mode: host

networks:
  default:
    driver: bridge

volumes:
 backend_storage:
