# Secret key (in hex) to generate the Homeserver's Keypair
secret_key = "0000000000000000000000000000000000000000000000000000000000000000"
# Domain to be published in Pkarr records for this server to be accessible by.
domain = "localhost"
# Port for the Homeserver to listen on.
# port = 15411
# Storage directory Defaults to <System's Data Directory>
storage = "/homeserver"

# event stream
default_list_limit = 500
max_list_limit = 10000
