# Secret key (in hex) to generate the Homeserver's Keypair
secret_key = "0123000000000000000000000000000000000000000000000000000000000000"
# Domain to be published in Pkarr records for this server to be accessible by.
domain = "localhost"
# Port for the Homeserver to listen on.
port = 6287
# Storage directory Defaults to <System's Data Directory>
storage = "/homeserver"

# event stream
default_list_limit = 500
max_list_limit = 10000

[admin]
# Set an admin password to protect admin endpoints.
# If no password is set, the admin endpoints will not be accessible. 
password = "admin"
# Set signup_mode to "open" to allow anyone to signup a new user,
# otherwise, "token_required" (the default) to require a valid invite token on signup;
signup_mode = "token_required"
