[api]
name = "nexusd.api"
public_ip = "172.18.0.3"
public_addr = "0.0.0.0:8080"
pubky_listen_socket = "0.0.0.0:8081"

[watcher]
name = "nexusd.watcher"
testnet = true
testnet_host = "homeserver"
homeserver = "8pinxxgqs41n4aididenw5apqp1urfmzdztr8jt4abrkdn435ewo"
events_limit = 1000
watcher_sleep = 100
moderation_id = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
moderated_tags = []

[stack]
log_level = "debug"
files_path = "/static/files/"

[stack.db]
redis = "redis://nexus-redis:6379"

[stack.db.neo4j]
uri = "bolt://nexus-neo4j:7687"
password = "12345678"
