# Redis configuration
# 16GB - adjust according to available system memory
maxmemory 17179869184
tcp-keepalive 0
tcp-backlog 65536
maxclients 30000
dir /data
save 60 1
save 30 10
save 10 100
appendonly yes
appendfsync everysec